--- #YAML:1.0
name:                BSD-Sysctl
version:             0.07
abstract:            Manipulate kernel sysctl variables on BSD-like systems
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Landgren
