--- #YAML:1.0
name:                BSD-Sysctl
version:             0.09
abstract:            Manipulate kernel sysctl variables on BSD-like systems
license:             perl
author:              
    - David Landgren
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
