--- #YAML:1.0
name:                BSD-Sysctl
version:             0.04
abstract:            Fetch sysctl values from BSD-like systems
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_04
author:              David Landgren
distribution_type:   module
requires:     
    XSLoader:                      0
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-new.html
    version: 1.1
